radicallyopensecurity/pentext

chatops/python/gitlab-to-pentext.py

This enhancement ignores the casing (not the spelling :wink: ) of the labels in gitlab.

Ignore casing of gitlab labels

---

chatops/python/validate_report.py

This fixes a bug when using `--spell` as well as `--learn`, to add words to the vocabulary

Fix: logmessage failed when learning new words

---

chatops/python/docbuilder.py

For consistency reasons, rename the default FOP configuration file that will be used to /etc/default/fop.xconf

Change default FOP configuration file: /etc/docbuilder/fop.xconf

---

chatops/python/pentext_id.py

Add script to facilitate easy conversion between report identifier and filename (gitlab) identifier.

Add pentext_id for conversion between report - filename identifiers

---

pull_upstream_changes.sh

The --force flag allows repositories not containing the PenText repository to
'update' to the latest version of PenText.

Support --force flag for 'new' PenText repositories

---

xml/xslt/findings2csv.xsl

This stylesheet outputs the findings from a report as CSV data.
It should be useful already but:
- it assumes the finding IDs are in sequential order;
- the description is currently expected as a single paragraph `<p>`
- recommendations are expected as a single paragraph, an unordered
list `<ul><li>...` or fallback to whatever else.

Import findings2csv.xsl

---

xml/xslt/placeholders.xslt

This allows users to count findings based on threatLevel, as well as based on one or more discrete status values.
Example in XML:
<finding_count threatLevel="High" status="new unresolved"/>
This will count the number of findings having attribute threatLevel="High", AND a status of either "new" OR "unresolved".
This change is backwards-compatible: Using finding_count without the status attribute will show the same results as before.

Add support for status attribute when using finding_count

---

xml/dtd/pentestreport.xsd
xml/xslt/placeholders.xslt

This PR allows the use of multiple status attributes, when using the `finding_count` element without any other attributes.
Example:
```
<finding_count status="unresolved resolved not_retested" />
```

Allow finding_count to use (multiple) status attribute values

---

xml/Makefile
xml/xslt/findings2json.xsl

These few commits import a new XSL transform to output (almost) compliant JSON output from the findings contained in a report.
I have tried to output the content of the description, technical description, impact, and recommendation without any line breaks (to respect the JSON format) and while sticking to what is available in XSLT 1.0 (if only for libxml2). I will welcome help to complete this correctly.

Add a template to export findings as JSON data

---

xml/xslt/pages.xslt

This PR allows coverpages without a specific background set:
When `frontpage_graphics.xml` contains for example the doctype `offerte`, and doesn't have a `file` specified.

feat: allow empty background graphics

---

xml/xslt/functions_params_vars.xslt

Pentext understands the service breakdown in hours or days, but not yet in business-weeks. To improve the visualization in the PDF file, this change adds support for business-weeks (shorthand weeks).
It is okay to call a business week just a "week" because on one hand it is the general understanding of authors and readers, but also it is broken down in hours in the final PDF version.

support business weeks in service breakdown

---

xml/xslt/inline.xslt

- Add support for markdown `~ strikethrough~` text.
When rendered to HTML strikethrough text is enclosed in a `<del>` inline element. This change converts it into a `fo:inline` element with according `text-decoration="line-through"` attribute.

support markdown line-through text

---

xml/doc/placeholders.md
xml/xslt/placeholders.xslt

This element can specify when a draft version of the report is due. Formatting
of the placeholder is similar to other dates (e.g. start and end date).

feat: add support for p_draftdue placeholder

---

xml/xslt/findings2csv.xsl

This XSLT properly exports findings to the CSV format.
Fields are enclosed using double quotes, and separated by commas.
Line breaks are removed.
The correct finding ID is being used.

fix: use quoting and correct number in CSV export

---

xslt/findings.xslt

This PR fixes the issue that when labels are set in a finding, the content of the labels is shown verbatim (outside of the header).

Fix: don't show the content of the labels in findings

---

xslt/generate_document.xsl

The current version of generic document didn't compile properly - this fixes that issue.

fix: ensure that (sample) generic documents can be created again

---

xslt/findings.xslt

Don't render `<labels>` in a `<finding>` tag.

fix: ignore template label tag

---

xslt/fo_inline.xslt

When converting code blocks with syntax highlighting hidden links get inserted into the HTML content. These are supposed to be used as hidden anchors to scroll to a referenced line of code. In a PDF document we do not need them, as findings are the level of anchors the document provides.
Instead of inserting an empty `(page 0)` reference, with this change such links simply get ignored.

feat: remove hidden inline links (aria-hidden=true)

---

xslt/auto.xslt

This PR does a small but meaningful step towards one of the sub-goals of #102 , namely to clarify the role of people mentioned in the testing team summary table.
Rendered example of how this looks on the example report:
Note the new subtitle `(pentester)` and `(approver)` in the left name column.

Add role classification to testing team listing

---

xslt/auto.xslt

The following changes add the ability to have labels and retest status directly into the summary of findings and recommendations tables. It also proposes a new layout for these tables, making them more space efficient.

New structural changes for summary of finding and recommendations

---

xslt/pages.xslt

When hiding top-level sections in a document by setting visibility to `hidden`, the resulting PDF may contain empty pages because the page layout is rendered, but without any content. To avoid this, the layout is only applied for sections that are not hidden.
Example to hide finding details, but leave the summary tables and charts:
```
<section id="findings" visibility="hidden">
...
</section>
```

[fix] skip layout for hidden sections
