radicallyopensecurity/pentext

chatops/python/gitlab-to-pentext.py, chatops/scripts/rosbot.coffee
Previously, when a required python package was missing, it would display a message containing the packages it needed. This has been expanded upon in two ways:
1) Installation instructions for the packages are now displayed
2) The missing package is also displayed.
=> Added extra verbosity in case of missing required packages + expanded rosbot's usage docs

chatops/README.md, chatops/python/gitlab-to-pentext.py
Implemented first rough version of markdown -> XML conversion. Note that this uses *pandoc*, which is a (new) prerequisite, as well as the *pypandoc* library:
```
pip install pypandoc
```
Closes #10
=> Implemented markdown -> XML conversion, closes #10

chatops/python/gitlab-to-pentext.py
Treat them accordingly. Note that the keyword can only be used in one note, and
has to be on the first line of the note.
Re-order notes (oldest note first).
=> Recognize keywords 'recommendation' and 'impact' in notes

chatops/python/gitlab-to-pentext.py
Big refactoring: added the basic Pentext classes: Finding and NonFinding.
These will soon be moved to their own Pentext library, together with all the other scripts / utilities.
=> Implemented true Unicode (UTF-8) support

chatops/python/docbuilder.py
Add exception handlers around git usage.
=> Make embedding git commit hash in the document an option (--tag)

chatops/python/validate_report.py
Pyenchant is a more abstract spelling back end, and can utilize aspell, as well as
hunspell.
Use titlecase module to validate whether titles are properly title cased.
Note that this change uses two new Python libraries, which should be installed:
- pyenchant
- titlecase
=> Change spelling back end to use pyenchant

xml/source/snippets/company_info.xml, xml/source/snippets/offerte/en/conditions.xml, xml/source/snippets/offerte/en/conditions_code-audit.xml, xml/source/snippets/offerte/nl/conditions.xml, xml/source/snippets/report/contact.xml
switched to single point of truth for company contact info & updated address/phone no
=> updated contact info

xml/source/snippets/offerte/en/planningandpayment.xml, xml/source/snippets/offerte/nl/planningandpayment.xml
=> updated payment period

xml/Makefile
Hi! I have written a Makefile to help with the generation of reports with pentext.
Before merging this pull-request, I think I found a bug, as per the output below:
```
$ (cd xml && make)
[...]
mkdir -p -- target
java -jar ../saxon9he.jar \
-s:"sample-report/source/report.xml" \
-xsl:"xslt/generate_report.xsl" \
-o:"target/report_sample-report.fo" \
-xi
Type error in xsl:when/@test on line 41 column 52 of numbering.xslt:
XPTY0004: Cannot compare xs:string to xs:boolean
at xsl:apply-templates (file:/home/khorben/Projects/ROS/pentext/xml/xslt/fo_inline.xslt#136)
processing /pentest_report/section[2]
at xsl:apply-templates (file:/home/khorben/Projects/ROS/pentext/xml/xslt/block.xslt#50)
processing /pentest_report/section[5]/section[1]/finding[12]/description[1]/p[1]/a[1]
at …
```
=> Import a Makefile for the sample report

chatops/bash/handler_build, chatops/python/docbuilder.py
Docbuilder now simply checks if there are other .fo files except for 'offerte' and 'report' then generates those.
=> simplified handling of multiple .fo files

xml/doc/report/Report Writing - Procedure.md
This PR has a minor addition to the documentation (the number and status attributes of a finding), as well as applies OPINIONATED formatting (Prettier) to markdown.
Theoretically this should make it easier to spot changes later on :)
=> Improve docs

xml/source/snippets/offerte/nl/methodology.xml
Apply opinionated XML formatting
=> feat: add section id for methodology

xml/source/snippets/offerte/nl/crystal-box.xml
@skyanth please review and merge, thanks :)
=> feat: correct typo, and use proper section tags

sample-report/source/findings/ace.xml, sample-report/source/findings/csrf.xml, sample-report/source/findings/dos.xml, sample-report/source/findings/information_leak.xml, sample-report/source/findings/password_reuse.xml, sample-report/source/findings/pe.xml, sample-report/source/findings/pe_management.xml, sample-report/source/findings/pe_management_2.xml, sample-report/source/findings/remote_code_execution.xml, sample-report/source/findings/spearphishing.xml, sample-report/source/findings/xss.xml, sample-report/source/findings/xss_netmon.xml, sample-report/source/future-work/juniper.xml, sample-report/source/future-work/vpn.xml, sample-report/source/non-findings/brute_force.xml, sample-report/source/non-findings/osw.xml, sample-report/source/non-findings/shielded_webapps.xml, sample-report/source/report.xml
=> feat: ensure sample report builds again

xslt/findings.xslt, xslt/styles.xslt
- Text and background color from attributes on /pentext_report/meta/labels/label
- List labels in finding header
=> Finding Labels

.gitignore, README.md, source/resultsinanutshell.xml, source/servicebreakdown.xml, source/snippets/company_info.xml, source/snippets/offerte/en/teamandreporting.xml, source/snippets/offerte/nl/teamandreporting.xml, templates/offerte/offerte_EN.xml, templates/offerte/offerte_NL.xml
Cherry-pick customizations prior to 2.0.
=> Cherry-pick customizations

doc/examples/examplegenericdocument.xml, doc/examples/examplereport.xml, doc/offerte/Offerte Writing Procedure.md, doc/offerte/offerte.html, doc/report/Report Writing - Procedure.md, doc/report/report.html, sample-report/source/report.xml, source/snippets/offerte/en/aboutus.xml, source/snippets/offerte/nl/aboutus.xml, templates/pentestreport/report.xml, xslt/off2rep.xsl
- Use HTTPS URLs for default scan tools
- Use HTTPS URL of ROS website
- Improve indentation
=> [chore] scan/pentest tools

doc/placeholders.md, dtd/invoice.xsd, dtd/offerte.xsd, dtd/pentestreport.xsd, source/snippets/offerte/en/introandscope.xml, source/snippets/offerte/en/introandscope_retest.xml, templates/offerte/offerte_EN.xml, templates/offerte/offerte_NL.xml, xslt/placeholders.xslt
- Make client postal code accessible as placeholder
- Note postal code in introduction
=> make client_postalcode available and include it in introduction

xslt/findings2csv.xsl
- Add retest status to CSV export
=> feat: add retest-status to CSV finding export

xslt/auto.xslt, xslt/findings.xslt, xslt/functions_params_vars.xslt, xslt/generate_report.xsl, xslt/styles.xslt
Adds the ability to create multiple tables for findings/recommendations which is useful in pentests where you have multiple targets. Also adds the ability to incldue labels for findings in the final report.
=> Adds the ability to create multiple tables for findings/recommendations

dtd/common.xsd
=> Pentest type enum

xslt/findings.xslt
Removing additional whitespace after line end.
=> chore: remove whitespace after xsl-values in findings.xslt

xslt/functions_params_vars.xslt
Express effort in weeks, not only days and hours.
=> feat: express effort in weeks (in addition to days)

source/futurework.xml
Recommending quarterly reports might be a bit too frequent. 😅 Reverting back to some older text.
=> chore: make futurework snippet less specific

.gitlab-ci.yml
- Add GitLab CI configuration file to automatically convert and build documents
=> feat: add .gitlab-ci.yml

xslt/off2rep.xsl, xslt/qs2offerte.xsl
Minor change to better document usage of ISO date string, OR 'TBD' (to be determined).
=> docs: better document usage of dates

doc/placeholders.md, dtd/common.xsd, sample-report/source/offerte.xml, sample-report/source/targets.xml, xslt/placeholders.xslt
This PR adds a number of new placeholders (`p_participants`, `p_location`), and fixes a previously broken one (`p_duration`).
Furthermore a sample quote (`offerte.xml`) is added, to see the new placeholders in action.
=> feat: add several new placeholders

xslt/auto.xslt, xslt/meta.xslt
- Add support for tested targets in report.xml
```xml
<target>
Frontend
<target>Core Application</target>
<target>Payment API</target>
</target>
```
=> [feat] nested meta targets

doc/RELEASE_NOTES.html, doc/examples/examplereport.xml, source/conclusion.xml, source/futurework.xml, source/snippets/offerte/en/conditions.xml, source/snippets/offerte/en/conditions_code-audit.xml, source/snippets/offerte/en/methodology_code-audit.xml, source/snippets/offerte/en/phishing.xml, source/snippets/offerte/en/projectoverview_code-audit.xml, source/snippets/offerte/nl/teamandreporting.xml, source/snippets/offerte/nl/teamandreporting_basic-scan.xml, templates/pentestreport/report.xml, xslt/off2rep.xsl
It would be really nice to apply some kind of coding standard; it's all horribly inconsistent. Meanwhile, here are some fixes for some small copy changes, and a bit of reformatting. You can cherry pick them if you like.
=> Fixes for numerous niggles

dtd/pentestreport.xsd
My IDE keeps flagging these items because they are not defined in the XSD, so I thought I'd fix that.
=> Add some definitions to XSD

xslt/fo_piecharts.xslt
Hey @ros-cr - this is the fix for #138 
Ready to be merged...
=> feat: don't use title casing by default in chart

.gitignore
Extend the `.gitignore` file to ignore more files.
=> Improve gitignore definition

sample-report/source/report.xml, templates/pentestreport/report.xml, xslt/off2rep.xsl
Change the capitalization of words in section titles, as discussed internally.
=> Correct section title casing

xslt/auto.xslt
These are the same changes to report structure as before but this time pushed to main instead of master.
=> Structural changes to layout pushed to main this time
